"""add_admin_table

Revision ID: 60ed3f7a4078
Revises: fa64e0e5db5c
Create Date: 2026-04-25 17:55:49.094985

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "60ed3f7a4078"
down_revision: Union[str, None] = "fa64e0e5db5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "weather_all_info",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("weather_id", sa.String(), nullable=False),
        sa.Column("weather_now_msg", sa.String(), nullable=True),
        sa.Column("weather_hours_msg", sa.LargeBinary(), nullable=True),
        sa.Column("weather_astro_msg", sa.String(), nullable=True),
        sa.Column("weather_5d_msg", sa.String(), nullable=True),
        sa.Column("weather_rain_msg", sa.String(), nullable=True),
        sa.Column("weather_wind_pressure_msg", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("weather_all_info")
    op.drop_table("admins")
    # ### end Alembic commands ###
