"""Initial

Revision ID: dac3025674a1
Revises: 
Create Date: 2026-04-15 17:25:45.701873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dac3025674a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_all_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('language_code', sa.String(), nullable=True),
    sa.Column('supports_inline_queries', sa.Boolean(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_all_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('weather_id', sa.String(), nullable=False),
    sa.Column('weather_now_msg', sa.String(), nullable=True),
    sa.Column('weather_hours_msg', sa.String(), nullable=True),
    sa.Column('weather_day_night_msg', sa.String(), nullable=True),
    sa.Column('weather_5d_msg', sa.String(), nullable=True),
    sa.Column('weather_rain_msg', sa.String(), nullable=True),
    sa.Column('weather_wind_pressure_msg', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_all_info')
    op.drop_table('user_all_info')
    # ### end Alembic commands ###
