"""added_weather_astro_table

Revision ID: fa64e0e5db5c
Revises: 6d55480b77ca
Create Date: 2026-04-17 15:35:04.934727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa64e0e5db5c'
down_revision: Union[str, None] = '6d55480b77ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_all_info', sa.Column('weather_astro_msg', sa.String(), nullable=True))
    op.drop_column('weather_all_info', 'weather_day_night_msg')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_all_info', sa.Column('weather_day_night_msg', sa.VARCHAR(), nullable=True))
    op.drop_column('weather_all_info', 'weather_astro_msg')
    # ### end Alembic commands ###
